{{- range $name, $svc := .Values.services }}
{{- if and $svc.enabled $svc.serviceAccount $svc.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $svc.serviceAccount.name | default $name }}
  namespace: {{ $.Values.global.namespace.name }}
{{- end }}
{{- end }}
