app:
  common-starter:
    security:
      enabled: false
server:
  port: 8080
spring:
  cloud:
    loadbalancer:
      health-check:
        initial-delay: 5s
        interval: 30s
        refetch-instances: true
        path:
          default: /actuator/health/readiness
        port: 9000
    gateway:
      server:
        webflux:
          discovery:
            service-labels:
              exposed: "true"
            locator:
              enabled: true
              lower-case-service-id: true
              predicates:
                - Path='/'+serviceId+'/api/**'
          default-filters:
            - TokenRelay=

# Override include. Others on common.starter
management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway