services:
  jenkins:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/usr/share/jenkins/ref/workspace/buildPipeline:ro
      - m2-cache:/root/.m2
    environment:
      CASC_JENKINS_CONFIG: /var/jenkins_home/workspace/buildPipeline/local-build/jenkins-casc.yaml
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
    extra_hosts: [ "host.docker.internal:host-gateway" ]
volumes:
  m2-cache: