namespace:
  name: marketplace

image:
  registry: localhost:5000
  tag: latest
  pullPolicy: Always

keycloak:
  realm: marketplace
  adminRealm: master
  adminClientId: admin-cli
  userClientId: marketplace-users

security:
  roles:
    goods:
      - name: GOODS_MANAGE_ROLE
        value: admin

secrets:
  postgresUser: user
  postgresPassword: password
  keycloakAdmin: user
  keycloakAdminPassword: password
  keycloakUserClientSecret: users-client-secret
