apiVersion: v1
kind: Secret
metadata:
  name: marketplace-secrets
  namespace: marketplace
type: Opaque
data:
  #  Temp for dev: user:password
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
