apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: {{ .Values.namespace.name }}
data:
  init.sql: |
    CREATE DATABASE goods;
    CREATE DATABASE users;
    CREATE DATABASE keycloak;
