apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: marketplace
  labels:
    app: users
    exposed: "true"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: users

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: localhost:5000/users:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: marketplace-secrets
            - configMapRef:
                name: global-config
