app:
  keycloak:
#    TODO: В k8s конфиге прописать
    server-url: "http://${KEYCLOAK_ADDR}/realms/${KEYCLOAK_REALM}"
    admin-realm: ${KEYCLOAK_ADMIN_REALM:master}
    client-id: ${KEYCLOAK_CLIENT_ID:admin-cli}
    username: ${KEYCLOAK_ADMIN}
    password: ${KEYCLOAK_ADMIN_PASSWORD}
    app-realm: ${KEYCLOAK_REALM:marketplace}

spring:
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_ADDR}/goods
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
