apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.5.0
          imagePullPolicy: IfNotPresent
          args:
            - start-dev
            - --import-realm
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - secretRef:
                name: keycloak-secret
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://postgres-keycloak:5432/keycloak
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_PROXY_HEADERS
              value: xforwarded
          volumeMounts:
            - name: realm-import
              mountPath: /opt/keycloak/data/import
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: realm-import
          configMap:
            name: keycloak-realm-import
