apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: marketplace
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: marketplace
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: keycloak/keycloak:26.0.5
          # TODO: start, not start-dev
          args: ["start-dev", "--import-realm"]
          env:
            - name: POSTGRES_ADDR
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: POSTGRES_ADDR

            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://${POSTGRES_ADDR}/keycloak

            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: marketplace-secrets
                  key: POSTGRES_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: marketplace-secrets
                  key: POSTGRES_PASSWORD
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: marketplace-secrets
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: marketplace-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
          volumeMounts:
            - name: realm-import
              mountPath: /opt/keycloak/data/import/
          ports:
            - containerPort: 8080
      volumes:
        - name: realm-import
          configMap:
            name: keycloak-realm-config