apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: marketplace/users-api:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
              name: http
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-users:5432/marketplace_users
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-users-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-users-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://keycloak:8080/realms/marketplace
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
