apiVersion: v1
kind: Secret
metadata:
  name: postgres-users-secret
  namespace: marketplace
type: Opaque
stringData:
  POSTGRES_DB: marketplace_users
  POSTGRES_USER: marketplace
  POSTGRES_PASSWORD: marketplace
