apiVersion: v1
kind: Service
metadata:
  name: postgres-users
  namespace: marketplace
spec:
  selector:
    app: postgres-users
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
