{{- if .Values.global.createGlobalSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: global-secret
  namespace: {{ .Values.global.namespace.name }}
type: Opaque
stringData:
{{- range $k, $v := .Values.global.secretData }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
