apiVersion: v1
kind: Secret
metadata:
  name: marketplace-secrets
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  KEYCLOAK_ADMIN: {{ .Values.secrets.keycloakAdmin | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.secrets.keycloakAdminPassword | quote }}
